### ISSUE TITLE
Refactor IAC, Other Bugs & Housekeeping

### ISSUE THREAD

**Issue by sparkplug0025** [gofractally/psibase#140]
Refactor IAC (inter-applet communication)
Let's do this work in small pieces so that each commit happens quickly and improves the situation piece by piece.

- [ ] refactor IAC out of rpc.mjs (it's current home) [moved to fractally applet board]
- [ ] Alternative to iFrameResizer? [bonus; low priority]
- [x] In Progress in #166: UI currently fails with a poor error message if a non-existent account is placed in the "To" field and submitted. This is because the iframe CommonSys system swallows errors. Either perform a lookup on the account field before allowing form submission first, or go ahead and fix it so that it's not swallowing errors. See TODO messages in `App.tsx` for more context and info.
- [x] Stop errors thrown from being swallowed in promises. (E.g.,`CommonSys::executeTransaction()` swallows errors when it fails.)
- [x] It would be great if the credit operation returned a value... wouldn't need an arbitrary `await`.
- [x] Why do we need so many arbitrary waits/delays? For example, line 43 in TokenSys `App.tsx`. There should be a way to signal that the iframe system is _ready_. 
- [x] `getLoggedInUser()` swallows errors when it fails.
- [x] We cannot currently retrieve a transfer date/time from the contract to display on items in the Transfer History table.

**Comment by cool-ant** [comment]
"Ensure the pending transaction gets cleared if there are any errors." item moved to fractally applet board

**Comment by James-Mart** [comment]
IAC has been entirely subsumed by the plugin architecture, closing
