### ISSUE TITLE
TokenSys: Signed-out state

### ISSUE THREAD

**Issue by brandonfancher** [gofractally/psibase#178]
If no user is logged in and they navigate directly to the TokenSys application, they just get this:

![Image](https://user-images.githubusercontent.com/7911424/192051497-c72297c9-755b-4c5c-a332-41106f5c4912.png)

What should they see? It should include a message or link or button to go to the Account app to log in, I'd imagine.

- [ ] design
- [ ] implement

**Comment by James-Mart** [comment]
Closing because token app deleted https://github.com/gofractally/psibase/pull/626
