### ISSUE TITLE
TokenSys: Toggle for "Manual debit" mode for user's account

### ISSUE THREAD

**Issue by brandonfancher** [gofractally/psibase#179]
A user can turn "manual debit" mode on their account on or off. When _off_, any tokens sent to them will automatically be received and added to their balance. When turned _on_, tokens sent to them will appear in their "Pending transfers" list until they Accept the tokens.

Currently, the only way for a user to toggle this on their account is...via the CLI?

We want to surface this setting in the Wallet / TokenSys applet.

This functionality is unique to Psibase...users will not know what this toggle means without some explanation. We need a means of introducing it to the user. Maybe that's a tooltip or an area with some explainer text? Tooltip is more implementation effort than just having text. Easier would be something like a section that includes the toggle AND explainer text...contained in a bounded area...possibly like this?

![Image](https://user-images.githubusercontent.com/7911424/192053041-3cd46ec2-e027-45da-a9f9-7414d455af21.png)

- [x] design
    - [x] the toggle itself
    - [x] an explainer to the user on the toggle
- [x] implementation

**Comment by James-Mart** [comment]
Closing because the wallet app is deleted
