### ISSUE TITLE
Better GraphQL support for subindices

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#214]
## Serving a TableIndex

Currently, to serve a TableIndex from GraphQL is very easily supported, for example:
```
struct TokenQuery
{
   auto balances() const
   {
      return tokenSys.index<BalanceTable, 0>();
   }
}:
PSIO_REFLECT(TokenQuery, method(balances))

optional<HttpReply> RTokenSys::serveSys(HttpRequest request)
{
   if (auto result = serveGraphQL(request, TokenQuery{}))
      return result;

   return nullopt;
}

```

## Serving a subindex

I want the syntax for a subindex to be similar, something like
```
auto balance(AccountNumber user) const
{ 
  return tokenSys.index<BalanceTable, 1>().subindex(user);
}
```

But the issue is that the system expects GraphQL queries for table indices have no user-defined parameters, and all params are the autogenerated ones, `gt, ge, lt, le, first, last, before, after`.

Currently the only way to do it is to call makeConnection automatically, for example (from the Auth RPC service):
```
struct AuthEcQuery
   {
      auto accWithKey(psibase::PublicKey key) const
      {
         auto idx = AuthEcSys::Tables{AuthEcSys::service}
                        .open<AuthEcSys::AuthTable>()
                        .getIndex<1>()
                        .subindex(key);
         return makeConnection<Connection<AuthRecord, "AuthConnection", "AuthEdge">>(
             idx, {}, {}, {}, {}, {}, {}, {}, {});
      }
   };
   PSIO_REFLECT(AuthEcQuery, method(accWithKey, key))
```

Is there any way we can get simpler syntax for subindices? @tbfleming @swatanabe

**Comment by tbfleming** [comment]
The workaround above is incomplete. Not declaring the `gt, ge, lt, le, first, last, before, after` arguments and passing `{}` instead disables paging.

**Comment by tbfleming** [comment]
There will always be a point where shortcuts don't cover a common use case, so the full machinery must be explicitly invoked. Have we reached a limit yet? I don't know, but having automatic machinery mix author-provided args with auto-generated args seems like a stretch.

**Comment by tbfleming** [comment]
I just had an idea which could remove some of the pain. This use of macros feels icky though.

```
#define MACRO_1(T) \
    optional<std::tuple<T>> gt, \
    optional<std::tuple<T>> ge, \
    ...

#define MACRO_2 gt, ge, ...
```

**Comment by swatanabe** [comment]
Rather than macros, we could have a way to expand a struct inline in the argument list:
```c++
auto balances(AccountNumber user, ConnectArgs rest);
...
method(balances, user, ...rest)
```

**Comment by swatanabe** [comment]
I think we should support merging arguments.  Although this makes the implementation considerably more complex, the interface specification is only slightly more complex.  Since the increase in interface complexity is mainly due to the restrictions on argument names, which users will very rarely need to care about, at a handwavy level it actually makes the interface simpler.

**Comment by James-Mart** [comment]
Recently serving a subindex was done using this trick
https://github.com/gofractally/psibase/pull/719
