### ISSUE TITLE
Add Continuous Integration Building and Testing for every PR

### ISSUE THREAD

**Issue by matt-langston** [gofractally/psibase#226]
I often times find that the main branch of psibase will not compile after I fetch and rebase, which is a costly encounter. The solution to this issue is to integrate continuous integration building and testing that runs for every PR so that any PR that fails CI is prevented from merging. This will keep the main branch clean and provide a positive and professional face to the psibase project.

**Comment by James-Mart** [comment]
Hmm, we actually do have ci/cd building and running tests on all PRs...
Do you perhaps need a `git submodule update --init --recursive`?

**Comment by matt-langston** [comment]
Can you point me to the CI logs?

**Comment by tbfleming** [comment]
https://github.com/gofractally/psibase/actions

**Comment by matt-langston** [comment]
Ah, CI is only running for Ubuntu 18.04. It is the macOS platform that is broken.

**Comment by tbfleming** [comment]
Maybe someday Apple will allow MacOS in VMs on non-Apple hardware for the purposes of CI/CD. Until then there's not much we can do without wasting a massive amount of funds.
