### ISSUE TITLE
Audit boot size

### ISSUE THREAD

**Issue by tbfleming** [gofractally/psibase#239]
The boot block is approaching the ~16MB triedent record size limit; it exceeds it when `--no-doc` isn't used.

**Comment by swatanabe** [comment]
It's now going over:
```
#8  0x0000000001b38eb9 in triedent::write_session::upsert (
    this=0x60c000000950, r=std::shared_ptr<triedent::root> (empty) = {...}, 
    key=std::span of length 4 = {...}, 
    val=std::span of length 16899736 = {...})
```

**Comment by swatanabe** [comment]
I found one culprit: d28f5fa7f12708605268b694d92d974847599c66 

The actual command executed is:
```
[19/21] cd .../rust-build && rm -rf ".../psibase/rust/psibase/boot-image/*" && mkdir ...
```
The double quotes added by cmake suppress glob expansion, which completely stops rm from doing anything.

ExploreSys generates unique file names on every build:
```
-rw-r--r--. 1 swatanabe swatanabe 24981 Dec  1 12:05 rust/psibase/boot-image/ExploreSys/ui/dist/dist/_app/immutable/start-686196bc.js
-rw-r--r--. 1 swatanabe swatanabe 24981 Dec  1 13:12 rust/psibase/boot-image/ExploreSys/ui/dist/dist/_app/immutable/start-4641986e.js
-rw-r--r--. 1 swatanabe swatanabe 24981 Dec  2 11:54 rust/psibase/boot-image/ExploreSys/ui/dist/dist/_app/immutable/start-0d06e378.js
-rw-r--r--. 1 swatanabe swatanabe 24981 Dec  2 11:59 rust/psibase/boot-image/ExploreSys/ui/dist/dist/_app/immutable/start-a7adb66b.js
-rw-r--r--. 1 swatanabe swatanabe 24981 Dec  2 12:06 rust/psibase/boot-image/ExploreSys/ui/dist/dist/_app/immutable/start-8350f546.js
-rw-r--r--. 1 swatanabe swatanabe 24981 Dec  2 12:17 rust/psibase/boot-image/ExploreSys/ui/dist/dist/_app/immutable/start-bc015141.js
-rw-r--r--. 1 swatanabe swatanabe 24981 Dec  2 12:23 rust/psibase/boot-image/ExploreSys/ui/dist/dist/_app/immutable/start-caec9844.js
-rw-r--r--. 1 swatanabe swatanabe 24981 Dec  2 12:29 rust/psibase/boot-image/ExploreSys/ui/dist/dist/_app/immutable/start-469e15ab.js
-rw-r--r--. 1 swatanabe swatanabe 24981 Dec  2 13:15 rust/psibase/boot-image/ExploreSys/ui/dist/dist/_app/immutable/start-6cacd3f9.js
-rw-r--r--. 1 swatanabe swatanabe 24981 Dec  5 07:41 rust/psibase/boot-image/ExploreSys/ui/dist/dist/_app/immutable/start-f1208428.js
...
```

Also, note how the behavior of cp changes when the directory exists, causing it to write to the wrong directory: `dist/dist`

@James-Mart

**Comment by James-Mart** [comment]
Just talked with steven about the boot block size, potential long term solution: 
* Construct the transactions needed for boot and add their hashes to the boot block. 
* Put the chain in a state that it will only accept the boot transactions until the chain is finished booting
* Schedule the boot transactions in subsequent blocks to deal with arbitrary boot sizes.

This way the chain ID remains dependent on all boot parameters/transactions by the fact that the genesis block will still contain hashes of all boot sequence operations.
