### ISSUE TITLE
Captured this may outlive object

### ISSUE THREAD

**Issue by tbfleming** [gofractally/psibase#258]
* `connection_manager::postconnect` captures `this` in `connection_base::on_disconnect` lambda
* `~peer_manager` destroys `autoconnector` (`connection_manager`) then destroys `_connections`
* `~connection_base` calls the lambda with the captured `this`

**Comment by tbfleming** [comment]
This isn't an immediate concern since only a graceful shutdown would cause it and we don't have graceful shutdown yet.

**Comment by swatanabe** [comment]
Yep. I have, in fact, observed this when exiting on an exception.
