### ISSUE TITLE
websocket_connection::async_write race in incoming connections

### ISSUE THREAD

**Issue by tbfleming** [gofractally/psibase#260]
`async_write`'s body executes in the stream's executor. On incoming connections, this is http's ioc, which has a thread pool. Multiple threads could be executing this body (from different write requests) while multiple threads could be executing `async_write_loop`'s body. All of these could be manipulating `outbox`.

**Comment by swatanabe** [comment]
The streams's executor is a strand for incoming connections. https://github.com/gofractally/psibase/blob/main/libraries/psibase_http/http.cpp#L1336
