### ISSUE TITLE
Potential races

### ISSUE THREAD

**Issue by tbfleming** [gofractally/psibase#261]
Path A:

* `peer_manager::async_recv`'s lambda runs from the sockets's executor
* Calls `peer_manager::disconnect`
   * Modifies `_connections` while running from the sockets's executor
   * This can happen from multiple sockets' executors
* Calls `websocket_connection::close`
* Modifies `closed` while running from the sockets's executor

Path B:

* main's `http_config->disconnect` inner lambda runs from `chainContext`
* Calls `peer_manager::disconnect`
   * Modifies `_connections` while running from chainContext
* Calls `websocket_connection::close`
* Modifies `closed` while running from chainContext

There appear to be more paths to `websocket_connection::close`.

**Comment by swatanabe** [comment]
`peer_manager::async_recv` dispatches back to `chainContext` before calling `disconnect`.
