### ISSUE TITLE
Captured this may outlive object

### ISSUE THREAD

**Issue by tbfleming** [gofractally/psibase#267]
* Multiple methods in `blocknet` capture `this` in calls to `direct_routing::async_send_block`, which calls `peer_manager::async_send`
* `peer_manager::async_send` also captures `this`
* Destruction of `node` may happen while async operations are queued
* Destruction of `chainContext` may also happen while async operations are queued

**Comment by swatanabe** [comment]
The easiest solution is to stop `chainContext` and the http server which will prevent any further callbacks from being executed.

**Comment by swatanabe** [comment]
Actually, only the http server needs to be stopped. If the main thread exits is obviously no longer running callbacks for `chainContext`.
