### ISSUE TITLE
Reconsider fracpack's single-representation goal

### ISSUE THREAD

**Issue by tbfleming** [gofractally/psibase#271]
Fracpack tries (but doesn't succeed at) having exactly 1 representation for any valid value. Consider dropping this goal. Doing so would remove these constraints:

* An empty vector or string must have a 0 offset. Check not implemented in Rust yet.
* If any field in a struct is optional, then all the remaining fields must also be optional. Check not implemented in Rust yet.
* If the last `n` optional fields are empty, then they must be omitted from `fixed_data`. Check not implemented in Rust yet. Rust encoder doesn't do the skipping yet.
* A bool must be 0 or 1. Check not implemented in Rust yet.

This rule should remain since it simplifies verification:
* Offset pointers must be in increasing order, not leave gaps, and not reuse storage. The non-reuse part prevents an amplification attack.

**Comment by tbfleming** [comment]
Note that some rules which are better off as compile-time checks (no non-optional after optional) end up being runtime checks in Rust since macro expansion can't reliably check for Optional because of type aliases and user-defined wrappers.

**Comment by swatanabe** [comment]
- I'm ambivalent about dropping the requirement on empty vectors and strings. It still requires a special case, and changing the definition from "MUST" to "MAY" is not a huge benefit.
- Non-optional after optional doesn't prevent a canonical representation. I agree that this should be dropped, but it's a separate issue. This rule seems to be intended to catch incorrect extensions, but is neither necessary nor sufficient for that purpose.
- Omitting trailing optional fields does have the benefit of allowing an old reader to know whether it has received any unknown fields. I don't think that's sufficient to justify the extra complexity, though.
- I would keep the requirement that bool is 0 or 1. It doesn't complicate the specification.

**Comment by tbfleming** [comment]
> changing the definition from "MUST" to "MAY" is not a huge benefit

In the Rust implementation, "MUST" requires either threading additional information through the decoders and checkers (even non-vectors would pay this cost for the extra field), duplicating code with only minor differences (specializing `embedded_variable_unpack` and `embedded_variable_verify` across the vector-like types), or adding a function to the trait with the only purpose to verify the rule.

The root problem: the size field must be 0 to represent empty when the object isn't pointed-to by an offset pointer.

**Comment by swatanabe** [comment]
I care a lot more about how hard and confusing it is to specify than about how hard it is to implement.

**Comment by swatanabe** [comment]
To be clear, I don't oppose dropping the empty container restriction. I don't have a strong opinion on it one way or the other.

**Comment by swatanabe** [comment]
There is an additional benefit to dropping trailing empty optional fields: A new struct that does not actually use any extended fields will not appear as extended when decoded as an old struct.
