### ISSUE TITLE
Failing transactions

### ISSUE THREAD

**Issue by Velua** [gofractally/psibase#308]
This error appears when running a fresh chain trying to send tokens between Alice and Bob. 
![Screenshot from 2023-02-04 14-16-42](https://user-images.githubusercontent.com/8017434/217665027-2314b15b-207b-48e5-9219-ee6685c45700.png)

**Comment by James-Mart** [comment]
* Was working at [def9c78](https://github.com/gofractally/psibase/commit/def9c7859bc9f1c88fe94d9ff9c3bdad5d6aae3d).
* Broken by [3554657](https://github.com/gofractally/psibase/commit/3554657b82e061b7bf6e9eb1b59162c5390ba8b2).

Reproduced by attempting to send tokens. Appears to be an issue with `/common/pack/SignedTransaction`.
![image](https://user-images.githubusercontent.com/42752296/218193610-1008daf6-e6cd-45a2-a4bb-c867238971e5.png)

**Comment by James-Mart** [comment]
Confirmed, fixed
