### ISSUE TITLE
Applet initialization should be made such a way that it avoid race conditions

### ISSUE THREAD

**Issue by sparkplug0025** [gofractally/psibase#325]
We found a race condition where the invite-sys was trying to execute the account-sys.storeKey operation, because whenever the invitation link is loaded it tries to persist the invitation PK. 

This operation persists a key to the browser local storage in the key `keyPairs`. 

Problem is that the account-sys has an initialization hook to also persist specific keys in the same localstorage key, it's inside the `useAccountsWithKeys` hook.

The implemented workaround was to not call the account-sys.storeKey during the invite-sys initialization anymore (see #324).

But we still did not solve the problem where an applet initialization might call another applet operation while that applet is initializing. We should implement a mechanism that the applet enqueue operations until it's really ready to initialize and process them.

**Comment by James-Mart** [comment]
Closing because applets are deprecated
