### ISSUE TITLE
IAC interface schemas

### ISSUE THREAD

**Issue by cool-ant** [gofractally/psibase#329]
Writeup on the topic with proposals
https://docs.google.com/document/d/1XDaYPYYnh0VgnpnvXZzRmNofasZPlo4P5D058YVHXG8/edit#heading=h.l2g8ylwwdgde

In particular, we would want to ensure we have a "Interface Schema", so devs know what client-side/applet actions they can call

**Comment by James-Mart** [comment]
This is (thankfully) completely handled by WIT interfaces and the wasm component model.
