### ISSUE TITLE
Docs update after db changes

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#367]
I think there are some docs that should be updated after the latest changes to the db.

Some sections to check
* [Sigany](https://github.com/gofractally/psibase/blob/main/doc/psidk/src/psibase/README.md#sigany) (Is this outdated?)
* [psinode](http://127.0.0.1:3000/psibase/index.html#psinode) (database-cache-size flag missing)

**Comment by swatanabe** [comment]
Sigany has not changed. database-cache-size is not documented yet, because I haven't finalized its behavior.
