### ISSUE TITLE
Psibase remote boot is a large request

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#381]
Trying to call push_boot with a local psibase on a remote server running nginx proxying to psinode fails because the request is ~8m in size. I could bump up the max allowed size of requests in nginx, but why is this request so big? 

From nginx access log
```
[error] 33#33: *296 client intended to send too large body: 8544049 bytes, client: 10.0.0.2, server: psibase.io, request: "POST /native/push_boot HTTP/2.0", host: "psibase.io"
```

The request:
```
psibase -a https://psibase.io boot --no-doc -k PUB_K1_7jTdMYEaHi66ZEcrh7To9XKingVkRdBuz6abm3meFbGw8zFFve -p myproducer
```

**Comment by swatanabe** [comment]
It this really different from #239 other than smaller limit? `psinode`'s http request limit is 20 MiB. maximum block size is 16 MiB.

**Comment by James-Mart** [comment]
Guess not, any reason to throttle webservers below the block limit?
