### ISSUE TITLE
Turn on SIMD by default in cmake config

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#383]

**Comment by swatanabe** [comment]
clang makes this needlessly difficult:
- clang runs `wasm-opt` if it is `$PATH`. There is no way to disable it or modify the invocation
- `wasm-opt` uses the `target_features` section to determine what features (beyond MVP) the wasm uses. If the wasm contains other instructions, it will fail
- `--strip-all` causes the `target_features` section to be removed *before* `wasm-opt` is run

**Comment by James-Mart** [comment]
Seems like `--strip-all` is the problem, then. Can we just use --strip-debug or are there other considerable space savings that --strip-all provides? Or some deeper reason for strip-all?
