### ISSUE TITLE
Psinode - Seg fault on admin-sys /#Logs page

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#413]
I am able to reproduce a psinode seg fault.

I have a local psinode running over https. Go to admin-sys, everything is fine until I access the /Logs page. After a few seconds on this page I get a seg fault.

CC @swatanabe

**Comment by James-Mart** [comment]
https://github.com/gofractally/psibase/assets/42752296/6e62264d-707d-468b-ba52-d34b662e72af

**Comment by swatanabe** [comment]
This happens because the socket is moved out of the session, but the session still thinks it has an active socket and tries to close it. The non-TLS implementation is fine, because it returns an error when trying to shutdown a moved-from socket, instead of crashing.
