### ISSUE TITLE
Replicate and/or mirror psibase content between instances

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#500]
## Goal

Explore the possiblity of a simple mechanism to transfer apps (services/applets) and potentially even state between instances of psibase.

## Justification

Psibase applications are likely to make heavy use of composability, even calling client-side actions to perform potentially complex action aggregation on the client-side before submitting transactions. This makes it difficult to test on local infrastructure because your application needs the logic defined in the applets deployed on a live instance.

## Other benefits

Perhaps whatever mechanism is designed to allow for the replication of state across instances can be shared to allow psibase boot to include third-party apps/services.

**Comment by swatanabe** [comment]
I don't think that this is a good way to approach the problem.  For starting a new chain, I think we're better off just making boot configurable. The fact that we have an existing chain that already has the services we want is kind of incidental to the goal here.

**Comment by James-Mart** [comment]
> we're better off just making boot configurable

I agree boot should be configurable, the functionality I envision could even be configurable with third-party apps/services that aren't part of our monorepo. 

>  incidental to the goal here

The goal as defined by the first use-case is explicitly the desire to replicate services/applets across instances. I am not proposing a solution as to how this would be accomplished, but I think it should be reasonably simple to set up my local chain with apps/services and potentially even state from another psibase instance for devs who don't want to test in prod.

Also I updated the description of this issue, because I want it to be more clear that this issue is more about cataloging the idea for future exploration than it is about working on any particular implementation.

**Comment by swatanabe** [comment]
> > we're better off just making boot configurable
> 
> I agree boot should be configurable, the functionality I envision could allow boot to be configurable with third-party apps/services that aren't part of our monorepo.
> 

I would prefer to have a way to bundle a service as a tarball or similar and allow either uploading it from a local file or pulling it from a URL.

**Comment by James-Mart** [comment]
Closing this as sufficiently addressed by the work done on supporting `.psi` packages.
