### ISSUE TITLE
Local Node Admin Hostname

### ISSUE THREAD

**Issue by bytemaster** [gofractally/psibase#517]
In order to deconflict the local node management UI from the chain hosted UI on the same http server we must define how things map.

Current mapping:
```
localhost => local admin panel 
hostname => common-sys.hostname  via mirroring the content
common-sys.hostname => clone of hostname (could cause cookie problems, etc) 
${account_name}.hostname works for all valid account names
```

Proposed Mapping:
```
localhost => local admin panel 
-admin.hostname => local admin panel if connecting from localhost, else presents a login prompt asking for node password
${account_name}.hostname works for all valid account names
hostname redirects to common-sys.hostname rather than server a clone of common-sys.hostname
``` 

account names cannot start with '-' so any subjective node hostnames can start that way.

Alternative proposal:
```
admin.-.hostname 
```
This makes all local subdomains a subdomain of '-.hostname' and allows us to add more subjective subdomains in the future.

Alternative proposal 2:
```
https://hostname => redirect to => https://common-sys.hostname/
https://hostname/admin does not redirect and works like -admin.hostname or admin.-.hostname 
```
The downside to this approach is that there is only one valid subdomain security level for local subjective endpoints.

**Comment by swatanabe** [comment]
I don't think that the goal of making the admin API non-conflicting with any possible on-chain service is particularly compelling. There are a few other names that are reserved for specific purposes as well.

- The name that we choose is user-visible, so aesthetics matters. Both the proposed mapping and alternative proposal are ugly, and probably harder to remember.
- For TLS, adding an additional level of subdomains requires adding it to the certificate subject.
- Alternative proposal 2 is definitely a bad idea.  It implies that root domain is served from the admin API and the admin API provides a redirect. This makes managing access control more complex and easier to mess up.

**Comment by swatanabe** [comment]
Another reason not to use `-admin`: `-admin.hostname` at the beginning of a line in plain text looks like it's intended to be a bullet point
