### ISSUE TITLE
CICD build race condition building wasm-loader ui files

### ISSUE THREAD

**Issue by brandonfancher** [gofractally/psibase#627]
There is a race condition intermittently impacting only Ubuntu 2004 builds on CICD on the `dev/plugins` branch and any branch off of that. I'm not able to reproduce this locally.

<img width="1028" alt="image" src="https://github.com/gofractally/psibase/assets/7911424/fb0526aa-e52c-48c6-8a9c-d2651c368097">

**Comment by brandonfancher** [comment]
Discovered in #626

**Comment by swatanabe** [comment]
Does `common-lib` need to build before `wasm-loader`?

**Comment by brandonfancher** [comment]
@swatanabe Yes, that's exactly the problem.

**Comment by brandonfancher** [comment]
Need to tackle this. Tagging #561 too.

**Comment by brandonfancher** [comment]
Soon, we'll make `wasm-loader` depend on `common-lib` as an external ES Module resource (already being served by CommonSys.) But for right now, as we're in active development of `wasm-loader`, it makes more sense to bundle it. Hence `wasm-loader`'s dependency on `common-lib`.

**Comment by brandonfancher** [comment]
#634 too.

**Comment by James-Mart** [comment]
This should be fixed [here](https://github.com/gofractally/psibase/pull/634/commits/1558448e7dad5fa5e9578185e1fceb7236db5cd4).
