### ISSUE TITLE
Implement getUser

### ISSUE THREAD

**Issue by Velua** [gofractally/psibase#629]
Add the ability for plugins to ask for the currently authenticated account. 

We could potentially use our `window.postMessage` to then present a toast notification or whatever else we plan on using for users to approve / deny messages. 
Once approved or denied, subsequent plugin calls will reveal the authenticated user.

**Comment by James-Mart** [comment]
The more generic capability is the flow for a plugin to popup a window asking for some authorization.
The call for get-user is already implemented here
https://github.com/gofractally/psibase/pull/645/files#diff-bcc34a6c2c14e6e17e53e63fe8af1e4031e68858eacd32eb3311d044ef0d5b11R7
