### ISSUE TITLE
Cargo psibase assumes local chain port

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#648]
`cargo psibase deploy` currently assumes the local chain is running at `http://psibase.127.0.0.1.sslip.io:8080/`. There is a `-a` flag for cargo psibase, but `cargo psibase -a http://psibase.127.0.0.1.sslip.io:8089/ deploy ...` still fails with: `error sending request for url (http://psibase.127.0.0.1.sslip.io:8080/common/tapos/head)`.

Instead, possible chain locations should be configured in a local environment file (perhaps `~/.psibase`), like:
```~/.psibase
dev=http://psibase.127.0.0.1.sslip.io:8079
prod=https://psibase.io:8080
```
Then we can use `cargo psibase deploy --host dev` to select the deploy target.

**Comment by Velua** [comment]
Sounds like the way to go! @James-Mart
