### ISSUE TITLE
`common-lib/messaging` library exposes too much

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#650]
UIs currently import things from `common-lib/messaging` such as `Supervisor`, but in fact the majority of the functionality exposed in the `messaging` library are just functions that should remain internal to the supervisor package. No one besides supervisor will use most of the functions related to plugin management.

I think most of the libraries for supervisor plugin management should be removed from common-lib and remain internal to the supervisor.

**Comment by Velua** [comment]
- Look and see if there is anything in messaging that makes sense to go somewhere else. Otherwise, run through with James.

**Comment by James-Mart** [comment]
Wasm-loader and supervisor items can be shared. What I'm trying to avoid is user facing libraries containing non-user-facing functionality. Consider moving those things that are intended for supervisor & loader but not end user UI into a `common-infra-lib`.
