### ISSUE TITLE
Add token UI + Plugin + Rust wrapper

### ISSUE THREAD

**Issue by Velua** [gofractally/psibase#694]
- [ ] Rust wrapper
- [ ] Token UI 
- [ ] Plugin

**Comment by Velua** [comment]
@James-Mart I'm thinking the mapping between a Token and a Symbol happens on the Symbol UI instead of the token, one less thing for the token UI to deal with and feels like more sense to redeem the thing you just bought all in the same UI.

**Comment by Velua** [comment]
I'm thinking the UI can have the `Tokens::recall` and `Tokens::burn` functionality all in the one form section, with a conditional field called `From` should you be the admin of the token, if left blank then it burns the users own balance. 

`Tokens::mapSymbol` to be `Symbols` problem. 

I'm thinking to debit manual token balances, we just have a table rendered under the transfer UI which displays a list of balances and who from with a button to redeem, can also add a "Redeem all". 
@James-Mart is there a pre-existing query I can use to call all manual credit balances of a particular user? Can't find it...

**Comment by James-Mart** [comment]
> the mapping between a Token and a Symbol happens on the Symbol UI

What if:
The symbol UI has "create token for your symbols" functionality, white-labeling token creation.
The token UI has, "assign symbol for your tokens" functionality, white-labeling symbol market interaction.

> The UI can have the Tokens::recall and Tokens::burn functionality all in the one form section
Personally I don't think either of these functions need to show up on any interface right now. We just need plugin functions for burn and recall to enable future UIs that require that functionality. If you feel inspired to create the interface for recall, I would think it should appear only on some kind of token-issuer administration page along with the core token parameterization (issuance schedule, etc), not on any kind of generic wallet page.

> table rendered under the transfer UI which displays a list of balances and who from with a button to redeem
Sounds good to me, there should be functionality to allow me both to uncredit balances that the recipient hasn't debited, and also to debit balances that I've been credited.

> is there a pre-existing query I can use to call all manual credit balances of a particular user
 This requires querying the `SharedBalanceTable` and there's not a very helpful query for it. Currently you can query the entire table, but we should remove that query and replace it with user-specific balance queries. Try to write the query - you can see an example of filtering by user in `userBalances` (in `RTokens.cpp`), you basically need to do the same thing but in `sharedBalances`.
