### ISSUE TITLE
Cargo-psibase version management

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#730]
Since `cargo-psibase` doesn't show up as a dependency in any cargo.toml, but `psibase` itself does (I think it's a dependency of every service, test, and plugin), it is going to be easy for them to get out of sync. This could cause non-obvious build errors.

What is the right way to ensure that the version of `cargo-psibase` stays up-to-date?

Option 1:
When `cargo-psibase` is building a service/test, it can check the version of psibase depended upon in that project's cargo.toml. Compare that version number with its own version. If its own version is != the version of psibase that the project is using... show a warning to the developer that there's a version mismatch.

Any other ideas?

**Comment by swatanabe** [comment]
Do we want to compare against the version in Cargo.toml or the version in the lockfile?
