### ISSUE TITLE
SPA 404 Support

### ISSUE THREAD

**Issue by Velua** [gofractally/psibase#758]
All our apps are created using `Vite` building as a `Single Page Appliation (SPA)`. 
This means both the JS and HTML all live in a single file `/index.html`. 

React SPA apps (like ours) that want the feel of multiple pages reach out for [React Router](https://reactrouter.com/en/main) which is a library that allows the user to move between components feeling like different pages but always remains at `/index.html`. 

So far, we've avoided the need for react router either by only having a single page per app or in the case of `XAdmin` we came up with a band-aid approach with conditional rendering in a ternary operator and hash routing. 

```
{activeItem === "Dashboard" ? (
                <DashboardPage />
            ) : activeItem === "Logs" ? (
                <LogsPage />
            ) : activeItem === "Peers" ? (
                <PeersPage
                    config={config}
                    peers={peers || []}
                    refetchConfig={refetchConfig}
                    refetchPeers={refetchPeers}
                />
            ) : activeItem === "Configuration" ? (
                <ConfigurationPage
                    config={config}
                    refetchConfig={refetchConfig}
                />
            ) : activeItem === "Boot" ? (
                <BootPage config={config} refetchConfig={refetchConfig} />
            ) : null}
```

In order to support things like `react-router` when deployed in production, web servers / services such as `Nginx`, `Apache` and `Vercel` are configured so that should a HTTP request go directly to `/cats` the server will not attempt to serve `/cats.html` and instead return `index.html` while retaining the `/cats` path, React Router will then run client side and identify the appropriate component to run. 

So, how do we make this happen for psibase?

**Comment by James-Mart** [comment]
Closing because:
This is actually already possible in psibase, since any rpc service can be written to return `index.html` in response to any request. 
There is one single exception: `x-admin`. This is because it is the one and only *native* service, and has no query service. There are workarounds we can use if we need `x-admin` to be an SPA.
