### ISSUE TITLE
Prevent accidental `deploy` of plugins

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#800]
Currently it's easily possible to mistakenly use `psibase deploy` instead of `psibase upload` when trying to upload a plugin. This causes the plugin to be successfully deployed to an account as though it is a service. This causes confusing errors when the VM tries to load the wasm plugin as though it is a module (probably fails at mapping imports step).

We should think of a way to prevent accidental deployment of plugins. Some kind of validation in setcode might be ideal, that way it's prevented regardless of whatever downstream tooling is used.

**Comment by swatanabe** [comment]
The `SetCode` service could parse the wasm at least enough to check imports.

**Comment by swatanabe** [comment]
This will become mostly moot once everything is using packages, since the package manager is not vulnerable to this kind of confusion.

**Comment by James-Mart** [comment]
> This will become mostly moot once everything is using packages, since the package manager is not vulnerable to this kind of confusion.

True. Is it entirely solved or would it still be possible to specify a plugin wasm as the service in the `toml` file?

**Comment by swatanabe** [comment]
It's technically possible to put a plugin as a service, but it's very unlikely to happen by accident. The build explicitly distinguishes services instead of using a generic verb like `deploy`.

**Comment by James-Mart** [comment]
Closing as not planned, given the above conversation. We are replacing individual wasm deployment with full package installation.
