### ISSUE TITLE
X-Admin form improvements

### ISSUE THREAD

**Issue by Velua** [gofractally/psibase#829]
> * [ ]  Rename BlockProducer name to NodeAccountName on the Join network flow.
> * [ ]  Connect to URL - Send a API request to check it's online and responding before moving to next page.

@Velua Were these completed?

_Originally posted by @James-Mart in https://github.com/gofractally/psibase/issues/742#issuecomment-2327495667_

**Comment by James-Mart** [comment]
Dup of #828
