### ISSUE TITLE
Rust `Schema` type needs ToSchema

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#845]
In order to wrap `Events::setSchema` (needed to call it inline from Rust services), the `Schema` type needs to implement `ToSchema`.

I took a quick look at this and it seemed to get complicated quickly, as it implies that `IndexMap` and `AnyType` also both need to implement `ToSchema`.

**Comment by swatanabe** [comment]
It won't actually be called, so `unimplemented!()` will work for now.

**Comment by James-Mart** [comment]
@cool-ant delivered [here](https://github.com/gofractally/psibase/commit/9db59f5d4d216c85b0b1ed5a6baeb9fdbf49b27a#diff-fefa1afab42fd33c885b44b61cfe56db34a140afeb08ceadd6c3d7b46a280be2R21)
