### ISSUE TITLE
Out of date README.md

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#862]
`Wasi SDK v20.0`, `llvm-16`, `clang` versions are all out of date in the readme since the update to wasi-sdk 24. Failed to remember this during code review of https://github.com/gofractally/psibase/pull/843

**Comment by swatanabe** [comment]
It isn't out-of-date yet, since we haven't broken compatibility the old version.

**Comment by James-Mart** [comment]
Okay, true
