### ISSUE TITLE
Package docs update

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#878]
# Background 

The package docs in `/doc/psidk/src/development/services/rust-service/package.md` do not clearly specify which package properties can/should/must appear in which crate, for multi-crate packages.

# Scope

The following rules should be added to the aforementioned `package.md` document:

## Package root crate

If the following fields are used at all, they must appear in the package root crate:
 * services
 * package-name

## Package service crate

If the following fields are used at all, they must appear in a package service crate:
* data
* plugin
* server
* flags

## Any crate

The following fields can be found in any crate, and the resulting package will union the definitions across all crates:
* postinstall
* dependencies

CC @swatanabe

**Comment by swatanabe** [comment]
They aren't organized by where they need to appear, but the descriptions mostly do specify where they are allowed.

**Comment by cool-ant** [comment]
What is the `service` field mentioned in the "service crate" section? @James-Mart

**Comment by James-Mart** [comment]
> What is the `service` field mentioned in the "service crate" section? @James-Mart

What service field? 😉
