### ISSUE TITLE
PsiNet landing page desktop

### ISSUE THREAD

**Issue by brandonfancher** [gofractally/psibase#91]
This ticket includes
- [x] Update of copy
- [x] styling of landing page
- [x] Links, Calls to Action
  - [x] link to testnet
  - [x] link to dev doc
- [ ] should be deployed/configured automatically when nodes deploy (consider moving this into a company monorepo and adding deployment to the build script)

Blocked
- [ ] include link to white paper

**Comment by James-Mart** [comment]
psinet defunct
