### ISSUE TITLE
account-sys applet: enable LoggedInUser and Signing (w applet spec)

### ISSUE THREAD

**Issue by cool-ant** [gofractally/psibase#94]
Create 2 separate sections, 1 for Create new account and 2 for Import an account

- [x] View your accounts
- [x] Login as one of them
- [x] Create a new account
-   [x] refresh accounts list once created
- [x] Logout: clear key from localStorage
- [x] Add existing account (Import by private key)
-   [x] generate pubKey when privKey is entered
- [ ] default selection of currentUser account

Define two operations:
- [x] getLoggedInUser
- [x] signTransaction

**Comment by Velua** [comment]
Stale
