### ISSUE TITLE
accounts-sys applet UX/design

### ISSUE THREAD

**Issue by cool-ant** [gofractally/psibase#95]
We need a design/look and feel we can implement for WebUIs. AccountsSys could serve as the one app to do the design on (we don't need every applet mocked out in high resolution).
AccountsSys will have the following functionality.
 - import privKey (comm to AccountSys)
 - create new account (only privileged (ƒractally team) accounts)
   - creator creates account, shares private key with Noob. Noob imports privKey.

**Comment by James-Mart** [comment]
Closing, will revisit upon recreation of account app
