### ISSUE TITLE
account-sys: add whitelist to account creation

### ISSUE THREAD

**Issue by cool-ant** [gofractally/psibase#96]
- [ ] Add contract that stores whitelist for testnet of which accounts are allowed to add new accounts.

Fractally accounts are hardcoded to be able to add and remove items from the whitelist.

Archived:
- Implement a way to kill an account, if someone is spamming our testnet. [testnet will be read-only to the public initially; so no need to kill an account].

**Comment by James-Mart** [comment]
account-sys and invite-sys are now the only accounts able to create accounts.
